name: CI Tests

on:
  pull_request:
  push:
    branches:    
      - master

jobs:
  build:
   runs-on: ubuntu-latest
   env:
     APP_ENV: production
     NODE_ENV: production
     PANOPTES_ENV: production
     CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
     CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
     CONTENT_ASSET_PREFIX: 'https://fe-content-pages.zooniverse.org'
     PROJECT_ASSET_PREFIX: 'https://fe-project.zooniverse.org'

   steps:
    # See: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#using-the-checkout-action
    - uses: actions/checkout@v2

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - run: yarn install --production=false
    - run: yarn workspace @zooniverse/react-components build
    - run: yarn workspace @zooniverse/classifier build

    - name: Cache project builds
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/packages/app-project/.next/cache
        key: ${{ runner.os }}-nextjs-project-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-project-

    - run: yarn workspace @zooniverse/fe-project build

    - name: Cache content pages builds
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/packages/app-content-pages/.next/cache
        key: ${{ runner.os }}-nextjs-content-pages-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-content-pages-

    - run: yarn workspace @zooniverse/fe-content-pages build
    - run: PANOPTES_ENV=test yarn test:ci
    - run: yarn coverage-lcov
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
